<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 *  Specific page output template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

	$sb_layout = weaverx_page_lead( '404', true );

	weaverx_sb_precontent('404');

		// and next the content area.
?>
		<article id="post-0" class="post error404 not-found">
			<?php
				$msg = apply_filters('weaverx_404_title', __('Sorry, no such page.','weaver-xtreme'));
				weaverx_page_title( $msg );

			if (!weaverx_getopt('_hide_not_found_search')) { ?>
				<div class="entry-content clearfix">
					<p><?php echo __( 'It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the menu links above, can help.','weaver-xtreme'); ?>
					</p>

				<?php
				get_search_form();
				echo "<p></p>\n";
				?>

				</div><!-- .entry-content -->
			<?php
			}      	// don't show not found message
			?>
		</article><!-- #post-0 -->

		<?php
	weaverx_page_tail( '404', $sb_layout );    // end of page wrap
?>
