<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 *   The Template for displaying all single posts.
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

	global $weaverx_cur_page_ID;
	$weaverx_cur_page_ID = get_the_ID();

	$sb_layout = weaverx_page_lead( 'single' );

	// and next the content area.
	weaverx_sb_precontent('single');

	// generate page content
    add_filter('the_content', 'add_walk_details', 5);
    function add_walk_details( $content ) {
        $slug = pods_v( 'last', 'url' ); 
        $walk = pods( 'walk', get_the_id() );
        if ( $walk->exists() ) {
            // add copyright notice
            $content .= '<p class="wis-ign-copyright">' . get_option('ign-copyright-text') . '</p>';
            if ($walk->field('gps_track_file')) {
                // We can show a route of this walk on a map - get the data prepared for showing it
                $content .= display_walk_map($walk);
            }
            $grade = $walk->field('walk_grade');
            $walk_grade = pods ('grade', $grade['term_id']);
            $content .= "<p>The grade of this walk is " . $walk->field('walk_grade.name') . ", which means <br/> " . $walk->field('walk_grade.description') . " </p>";
            $content .= '<table class="wis-single-walk-table" style="width:100%">';
            $content .= "<tr><td>Nearest town</td><td>" . $walk->field('town') . "</td></tr>";
            $place = $walk->field('walk_place');
            if ($place) {
                $walk_place = pods ('place', $place['term_id']);
                $latlng = $walk_place->field('latitude') . ", " .  $walk_place->field('longitude');
                $directions = $walk_place->display('description');
            } else {
                $latlng = $walk->field('start_point_latitude') . ", " . $walk->field('start_point_longitude');
                $directions = $walk->display('directions_to_start');
            }
            $content .= "<tr><td>Directions to start</td><td>$directions</td></tr>";
            $content .= "<tr><td>Start point (Lat/Long)</td><td>" . $latlng . '<br>Click <a href="https://maps.google.com/maps?q=loc:' . $latlng . '" target="_blank">here</a> to view in Google Maps (in a new browser tab)</td></tr>';
            $content .= "<tr><td>Length (km)</td><td>" . $walk->field('distance') . "</td></tr>";
            $content .= "<tr><td>Ascent (metres)</td><td>" . $walk->field('ascent') . "</td></tr>";
            $content .= "<tr><td>Walking time (hours)</td><td>" . $walk->field('walking_time') . "</td></tr>";
            $content .= "<tr><td>Total time (hours)</td><td>" . $walk->field('total_time') . "</td></tr>";
            $content .= "<tr><td>Recommendations or Restrictions</td><td>" . $walk->field('restrictions') . "</td></tr>";
            $content .= "</table>\n\n<br/><br/><p><br/><br>";
            $wdf = $walk->field('walk_description_file');
            $content .= '<a class="wis-single-walk-button" href="'. $wdf['guid'] . '">Download walk description</a>';
            if ($walk->field('gps_track_file')) {
                $gpx = $walk->field('gps_track_file');
                $content .= '<a class="wis-single-walk-button" download href="'. $gpx['guid'] . '">Download GPS file</a>';
            }
            if ($walk->field('photo')) {
                $content .= '<div class="wis-photos">';
                for ($i = 0; $i < count($walk->field('photo')); $i++) {
                    $photos = $walk->field('photo');
                    $photo = $photos[$i];
                    $img = wp_get_attachment_url( $photo['ID'] );
                    $alt = $photo['post_title'];  // set the image Alt Text to be the filename
                    $content .= '<figure class="wis-single-walk-photo">';
                    $content .= '<img class="attachment-medium_large size-medium_large" src="' . $img . '" alt="' . $alt . '" scale="0" width="300" height="225">';
                    $content .= "<figcaption>" . $photo['post_excerpt'] . "</figcaption>";
                    $content .= "</figure>";
                    $content .= '<p style="visibility:hidden; margin: 0; border: 0; padding: 0"></p>';
                }
                $content .= "</div>";
            }
        }  
        return $content;
    }
    

	$cats = weaverx_getopt_checked('single_nav_link_cats');
	while ( have_posts() ) {
		weaverx_post_count_clear();
		the_post(); ?>
	<nav id="nav-above" class="navigation">
	<h3 class="assistive-text"><?php echo __( 'Post navigation','weaver-xtreme'); ?></h3>
	<?php if (weaverx_getopt('single_nav_style')=='prev_next') { ?>
		<div class="nav-previous"><?php previous_post_link( '%link', __( '<span class="meta-nav">&larr;</span> Previous','weaver-xtreme'), $cats ); ?></div>
		<div class="nav-next"><?php next_post_link( '%link', __( 'Next <span class="meta-nav">&rarr;</span>','weaver-xtreme'), $cats); ?></div>
	<?php } else { ?>
		<div class="nav-previous"><?php previous_post_link( '%link', '<span class="meta-nav">' . _x( '&larr;', 'Previous post link','weaver-xtreme') . '</span> %title', $cats ); ?>
		</div>
		<div class="nav-next"><?php next_post_link( '%link', '%title <span class="meta-nav">' . _x( '&rarr;', 'Next post link','weaver-xtreme') . '</span>' , $cats); ?></div>                 <?php } ?>
	</nav><!-- #nav-above -->

	<?php get_template_part( 'templates/content', 'single' ); ?>

	<nav id="nav-below" class="navigation">
	<h3 class="assistive-text"><?php echo __( 'Post navigation','weaver-xtreme'); ?></h3>
	<?php if (weaverx_getopt('single_nav_style')=='prev_next') { ?>
		<div class="nav-previous"><?php previous_post_link( '%link', __( '<span class="meta-nav">&larr;</span> Previous','weaver-xtreme'), $cats ); ?></div>
		<div class="nav-next"><?php next_post_link( '%link', __( 'Next <span class="meta-nav">&rarr;</span>','weaver-xtreme'), $cats ); ?></div>
	<?php } else { ?>
		<div class="nav-previous"><?php previous_post_link( '%link', '<span class="meta-nav">' . _x( '&larr;', 'Previous post link','weaver-xtreme') . '</span> %title', weaverx_getopt_checked('single_nav_link_cats') ); ?></div>
		<div class="nav-next"><?php next_post_link( '%link', '%title <span class="meta-nav">' . _x( '&rarr;', 'Next post link','weaver-xtreme') . '</span>', $cats ); ?></div>
	<?php } ?>
	</nav><!-- #nav-above -->

	<?php comments_template( '', true );

	} // end of the loop.

	weaverx_sb_postcontent('single');

	weaverx_page_tail( 'single', $sb_layout );    // end of page wrap
?>
